# Generated by Django 4.2.4 on 2023-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
