# Generated by Django 4.2.4 on 2023-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_user_session_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('country_code', models.PositiveIntegerField()),
                ('languages', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh-cn', 'Chinese (Simplified)'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ko', 'Korean'), ('tr', 'Turkish'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('cs', 'Czech'), ('sv', 'Swedish'), ('ro', 'Romanian'), ('hu', 'Hungarian'), ('vi', 'Vietnamese'), ('el', 'Greek'), ('th', 'Thai'), ('he', 'Hebrew'), ('id', 'Indonesian'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('hr', 'Croatian'), ('fa', 'Persian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('ms', 'Malay'), ('et', 'Estonian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('sr', 'Serbian'), ('sw', 'Swahili'), ('tl', 'Tagalog'), ('is', 'Icelandic'), ('ka', 'Georgian'), ('hy', 'Armenian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('kk', 'Kazakh'), ('az', 'Azerbaijani'), ('ky', 'Kyrgyz'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('ne', 'Nepali'), ('pa', 'Punjabi'), ('si', 'Sinhala'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('or', 'Odia'), ('as', 'Assamese'), ('my', 'Burmese'), ('dz', 'Dzongkha'), ('km', 'Khmer'), ('lo', 'Lao'), ('mn', 'Mongolian'), ('my', 'Burmese'), ('ne', 'Nepali'), ('ps', 'Pashto'), ('sd', 'Sindhi'), ('tg', 'Tajik'), ('tk', 'Turkmen'), ('ug', 'Uighur'), ('ur', 'Urdu'), ('yi', 'Yiddish')], max_length=50)),
                ('photo_url', models.URLField()),
                ('session_message', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('reviews', models.TextField(max_length=255)),
            ],
        ),
    ]
