# Generated by Django 4.2.4 on 2023-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
