# Generated by Django 4.2.4 on 2023-09-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='photos',
            field=models.URLField(),
        ),
    ]
