# Generated by Django 4.2.4 on 2023-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh-cn', 'Chinese (Simplified)'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ko', 'Korean'), ('tr', 'Turkish'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('cs', 'Czech'), ('sv', 'Swedish'), ('ro', 'Romanian'), ('hu', 'Hungarian'), ('vi', 'Vietnamese'), ('el', 'Greek'), ('th', 'Thai'), ('he', 'Hebrew'), ('id', 'Indonesian'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('hr', 'Croatian'), ('fa', 'Persian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('ms', 'Malay'), ('et', 'Estonian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('sr', 'Serbian'), ('sw', 'Swahili'), ('tl', 'Tagalog'), ('is', 'Icelandic'), ('ka', 'Georgian'), ('hy', 'Armenian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('kk', 'Kazakh'), ('az', 'Azerbaijani'), ('ky', 'Kyrgyz'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('mr', 'Marathi'), ('ne', 'Nepali'), ('pa', 'Punjabi'), ('si', 'Sinhala'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('or', 'Odia'), ('as', 'Assamese'), ('my', 'Burmese'), ('dz', 'Dzongkha'), ('km', 'Khmer'), ('lo', 'Lao'), ('mn', 'Mongolian'), ('my', 'Burmese'), ('ne', 'Nepali'), ('ps', 'Pashto'), ('sd', 'Sindhi'), ('tg', 'Tajik'), ('tk', 'Turkmen'), ('ug', 'Uighur'), ('ur', 'Urdu'), ('yi', 'Yiddish')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
