# Generated by Django 4.2.4 on 2023-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_address_customuser_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
