# Generated by Django 4.2.4 on 2023-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_guide_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='background_URL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
