# Generated by Django 4.2.4 on 2023-09-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_guide_background_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='photos',
            new_name='personal_photo',
        ),
    ]
