# Generated by Django 4.2.4 on 2023-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_photos_guide_personal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
