# Generated by Django 4.2.4 on 2023-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
