# Generated by Django 4.2.4 on 2023-09-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_guide_is_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='is_guide',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
