# Generated by Django 4.2.4 on 2023-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_guidesreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='license',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
