# Generated by Django 4.2.4 on 2023-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_tourslist_guide'),
        ('login', '0008_guide_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guided_tours',
            field=models.ManyToManyField(blank=True, related_name='guides', to='tours.tourslist'),
        ),
    ]
