# Generated by Django 4.2.4 on 2023-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_customuser_guided_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
