# Generated by Django 4.2.4 on 2023-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_guide_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_url',
            field=models.ImageField(blank=True, default='https://www.pngarts.com/files/10/Default-Profile-Picture-Download-PNG-Image.png', null=True, upload_to='p_images'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='background_URL',
            field=models.ImageField(blank=True, null=True, upload_to='b_images'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='personal_photo',
            field=models.ImageField(blank=True, default='https://www.pngarts.com/files/10/Default-Profile-Picture-Download-PNG-Image.png', null=True, upload_to='p_images'),
        ),
    ]
