# Generated by Django 4.2.4 on 2023-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_tourslist_guide'),
        ('login', '0012_alter_customuser_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='tours',
            field=models.ManyToManyField(blank=True, to='tours.tourslist'),
        ),
    ]
