# Generated by Django 4.2.4 on 2023-09-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_customuser_guided_tours_remove_guide_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='background_URL',
        ),
    ]
