# Generated by Django 4.2.4 on 2023-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourslist',
            name='state_id',
            field=models.PositiveIntegerField(),
        ),
    ]
