# Generated by Django 4.2.4 on 2023-09-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourslist_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourslist',
            old_name='tour_location',
            new_name='location',
        ),
    ]
