# Generated by Django 4.2.4 on 2023-09-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_tour_location_tourslist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourslist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
