# Generated by Django 4.2.4 on 2023-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourslist_message_tourslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourslist',
            name='state_id',
            field=models.CharField(choices=[('1', 'Cairo'), ('2', 'Alexandria'), ('3', 'Giza'), ('4', 'Luxor'), ('5', 'Aswan'), ('6', 'Asyut'), ('7', 'Beheira'), ('8', 'Beni Suef'), ('9', 'Dakahlia'), ('10', 'Damietta'), ('11', 'Faiyum'), ('12', 'Gharbia'), ('13', 'Ismailia'), ('14', 'Kafr El Sheikh'), ('15', 'Matrouh'), ('16', 'Minya'), ('17', 'Monufia'), ('18', 'New Valley'), ('19', 'North Sinai'), ('20', 'Port Said'), ('21', 'Qalyubia'), ('22', 'Qena'), ('23', 'Red Sea'), ('24', 'Sharqia'), ('25', 'Sohag'), ('26', 'South Sinai'), ('27', 'Suez'), ('28', '6th of October'), ('29', 'Helwan'), ('30', '15th of May'), ('31', '10th of Ramadan')], max_length=2),
        ),
    ]
