# Generated by Django 4.2.4 on 2023-09-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourslist_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourslist',
            old_name='state_id',
            new_name='state',
        ),
    ]
