# Generated by Django 4.2.4 on 2023-09-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_state_id_tourslist_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourslist',
            old_name='state',
            new_name='state_id',
        ),
    ]
