# Generated by Django 4.2.4 on 2023-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_rename_state_tourslist_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='rate',
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
