# Generated by Django 4.2.4 on 2023-09-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tourslist_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourslist',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
