# Generated by Django 4.2.4 on 2023-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tourslist_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
