# Generated by Django 4.2.4 on 2023-09-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tourslist_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='tourslist',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourslist',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourslist',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourslist',
            name='review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tours.reviews'),
            preserve_default=False,
        ),
    ]
