# Generated by Django 4.2.4 on 2023-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tourslist_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourslist',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
