# Generated by Django 4.2.4 on 2023-09-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_reviews_tourslist_description_tourslist_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourslist',
            name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tours.tourslist'),
            preserve_default=False,
        ),
    ]
