# Generated by Django 4.2.4 on 2023-09-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourslist_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourslist',
            name='guide',
        ),
    ]
