# Generated by Django 4.2.4 on 2023-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='photo',
            field=models.ImageField(default='', upload_to='tours'),
            preserve_default=False,
        ),
    ]
