# Generated by Django 4.2.5 on 2023-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_tourslist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourslist',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
