# Generated by Django 4.2.4 on 2023-09-15 16:53

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_tourslist_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourslist',
            name='photo',
            field=models.ImageField(blank=True, default=tours.models.default_tour_photo, null=True, upload_to='tours/'),
        ),
    ]
