# Generated by Django 4.2.4 on 2023-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_bannar_bannar_url_alter_sliderphoto_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannar',
            name='bannar_url',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='sliderphoto',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
